Fix Savannah snapshot downloads by switching from cgit to gitweb
The cgit snapshot service on Savannah GNU.org has been disabled/broken,
returning HTTP 400 errors for all snapshot requests. This affects the
emacs update CI job which downloads source tarballs for building.

The error manifested as:
  error: unable to download 'https://git.savannah.gnu.org/cgit/emacs.git/snapshot/emacs-<sha>.tar.gz': HTTP error 400

This is a known infrastructure issue affecting multiple projects:
- https://lists.gnu.org/r/guix-devel/2025-01/msg00170.html
- https://github.com/NixOS/nixpkgs/issues/346264

The recommended workaround from the Guix community discussion is to use
gitweb URLs instead of cgit URLs for downloading snapshots:
  Old: https://git.savannah.gnu.org/cgit/emacs.git/snapshot/emacs-<sha>.tar.gz
  New: https://git.savannah.gnu.org/gitweb/?p=emacs.git;a=snapshot;h=<sha>;sf=tgz

The --name flag is required because gitweb URLs contain semicolons which
nix-prefetch-url incorrectly interprets as part of the store path name.